//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentData
    {
        public int ST_ID { get; set; }
        public string ST_Name { get; set; }
        public Nullable<int> ST_Age { get; set; }
        public string Email { get; set; }
        public string ST_Pass { get; set; }
        public string AY_Name { get; set; }
        public string CRS_Name { get; set; }
        public int ST_Grade { get; set; }
    }
}
