//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherData
    {
        public int T_ID { get; set; }
        public string T_Name { get; set; }
        public Nullable<int> T_Salary { get; set; }
        public string Email { get; set; }
        public string T_Pass { get; set; }
        public string CRS_Name { get; set; }
        public Nullable<int> T_Evaluation { get; set; }
    }
}
